[package]
name = "TriangleTurning_2_6_2026"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl2 = { version = "0.38.0", features = ["gfx"] }

[[bin]]
name = "p1"
path = "src/p1.rs"

[[bin]]
name = "p2"
path = "src/p2.rs"

[[bin]]
name = "p3"
path = "src/p3.rs"

[[bin]]
name = "p4"
path = "src/p4.rs"

[[bin]]
name = "p5"
path = "src/p5.rs"

[[bin]]
name = "p6"
path = "src/p6.rs"

[[bin]]
name = "p7"
path = "src/p7.rs"

[[bin]]
name = "p8"
path = "src/p8.rs"